=== M4TT30-4RZ4N1/DP2--2017-2018/Assignment1/xsd/nfvInfo.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema targetNamespace="http://www.example.com/nfvInfo"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:nfv="http://www.example.com/nfvInfo"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="1.0"
	elementFormDefault="unqualified">


	<xsd:annotation>
		<xsd:documentation>
			VirtualNetworkManager schema for Assignment 1 of the course Distributed Programming II
			2017/2018 in Politechnic University of Turin.
			This XML Schema file was developed by Matteo Arzani.
		</xsd:documentation>
	</xsd:annotation>

	<!-- definition of simple elements -->

	<!-- definition of basic attributes -->	
	<xsd:attributeGroup name="deployTimeGroup">
		<xsd:attribute name="deployTime" type="xsd:dateTime"
			use="required" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="memoryGroup">
		<xsd:attribute name="memory" type="xsd:nonNegativeInteger"
			use="required" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="diskGroup">
		<xsd:attribute name="disk" type="xsd:nonNegativeInteger"
			use="required" />
	</xsd:attributeGroup>
	
	<xsd:attributeGroup name="maxLGroup">
		<xsd:attribute name="maxL" type="xsd:nonNegativeInteger"
			use="optional" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="avglatencyGroup">
		<xsd:attribute name="latency" type="xsd:nonNegativeInteger"
			use="required" />
	</xsd:attributeGroup>

	<xsd:attributeGroup name="maxVNFGroup">
		<xsd:attribute name="maxVNF" type="xsd:nonNegativeInteger"
			use="required" />
	</xsd:attributeGroup>


	<!-- definition of root -->
	<xsd:element name="virtualnetworkmanager">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nfv:catalog" minOccurs="1" maxOccurs="1">
				</xsd:element>
				<xsd:element ref="nfv:nffg" minOccurs="0" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element ref="nfv:in" minOccurs="1" maxOccurs="1">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>

		<!-- Each nffg has a unique @name (root) ! -->
		<xsd:key name="nffg_key">
			<xsd:selector xpath="nfv:nffg"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>

		<!-- Each node has a unique @name (root) ! -->
		<xsd:key name="node_key">
			<xsd:selector xpath="nfv:nffg/nfv:node"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>
				
		<!-- Each link reference to two nodes -->
		<xsd:keyref name="node_key_ref1" refer="nfv:node_key">
			<xsd:selector xpath="nfv:nffg/nfv:link"></xsd:selector>
			<xsd:field xpath="@src"></xsd:field>
		</xsd:keyref>

		<xsd:keyref name="node_key_ref2" refer="nfv:node_key">
			<xsd:selector xpath="nfv:nffg/nfv:link"></xsd:selector>
			<xsd:field xpath="@dst"></xsd:field>
		</xsd:keyref>
		
		<!-- Each vnft has a unique @name ! inside the catalog -->
		<xsd:key name="vnft_key">
			<xsd:selector xpath="nfv:catalog/nfv:vnft"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>
		
		<!-- Each node reference to a specific vnft -->
		<xsd:keyref name="vnft_key_ref" refer="nfv:vnft_key">
			<xsd:selector xpath="nfv:nffg/nfv:node"></xsd:selector>
			<xsd:field xpath="@vnft"></xsd:field>
		</xsd:keyref>
							
	</xsd:element>

	<!-- Definition of other virtual elements -->

	<xsd:element name="catalog">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nfv:vnft" minOccurs="1" maxOccurs="unbounded">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
							
	</xsd:element>

	<xsd:element name="vnft">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
			<xsd:attributeGroup ref="nfv:memoryGroup"></xsd:attributeGroup>
			<xsd:attributeGroup ref="nfv:diskGroup"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="nffg">

		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nfv:node" minOccurs="1" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element ref="nfv:link" minOccurs="0" maxOccurs="unbounded">
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attributeGroup ref="nfv:deployTimeGroup"></xsd:attributeGroup>
		</xsd:complexType>
				
	<!-- Each link has a unique @name inside an nffg ! -->
		<xsd:key name="link_key">
			<xsd:selector xpath="nfv:link"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>

	</xsd:element>

	<xsd:element name="node">
		<xsd:complexType>
			<!-- the name is an ID cause is referenced from the ih -->
			<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
			<xsd:attribute name="vnft" type="xsd:token" use="required"></xsd:attribute>
		</xsd:complexType>
				
	</xsd:element>

	<xsd:element name="link">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attribute name="src" type="xsd:IDREF" use="required">
			</xsd:attribute>
			<xsd:attribute name="dst" type="xsd:IDREF" use="required">		
			</xsd:attribute>
			<xsd:attribute name="throughput" use="optional">
				<xsd:simpleType>
		   			 <xsd:restriction base="xsd:double">
		      			<xsd:minInclusive value="0"/>
		    		</xsd:restriction>
		    	</xsd:simpleType>
			</xsd:attribute>
			<xsd:attributeGroup ref="nfv:maxLGroup"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

	<!-- Definition of other physical elements -->

	<xsd:element name="in">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nfv:host" minOccurs="1" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element ref="nfv:connection" minOccurs="0"
					maxOccurs="unbounded">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>

	<!-- Each host has a unique @name inside the in -->
		<xsd:key name="host_key">
			<xsd:selector xpath="nfv:host"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
		</xsd:key>
		
		<!-- Each connection reference to two host -->
		<xsd:keyref name="host_key_ref1" refer="nfv:host_key">
			<xsd:selector xpath="nfv:connection"></xsd:selector>
			<xsd:field xpath="@h1"></xsd:field>
		</xsd:keyref>
		
		<xsd:keyref name="host_key_ref2" refer="nfv:host_key">
			<xsd:selector xpath="nfv:connection"></xsd:selector>
			<xsd:field xpath="@h2"></xsd:field>
		</xsd:keyref>
		
	</xsd:element>

	<xsd:element name="host">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attributeGroup ref="nfv:maxVNFGroup"></xsd:attributeGroup>
			<xsd:attributeGroup ref="nfv:memoryGroup"></xsd:attributeGroup>
			<xsd:attributeGroup ref="nfv:diskGroup"></xsd:attributeGroup>
			<!-- This attribute is a list of names of nodes -->
			<xsd:attribute name="nodes" type="xsd:IDREFS" use="optional">			
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="connection">
		<xsd:complexType>
			<xsd:attribute name="h1" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attribute name="h2" type="xsd:token" use="required"></xsd:attribute>
			<xsd:attribute name="throughput" use="optional">
				<xsd:simpleType>
		   			 <xsd:restriction base="xsd:double">
		      			<xsd:minInclusive value="0"/>
		    		</xsd:restriction>
		    	</xsd:simpleType>
			</xsd:attribute>
			<xsd:attributeGroup ref="nfv:avglatencyGroup"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

<!-- This XML Schema file was developed by Matteo Arzani for the Assignment 
	1 of the course Distributed Programming II 2017/2018 in Politechnic University 
	of Turin. -->

=== M4TT30-4RZ4N1/DP2--2017-2018/Assignment1/xsd/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<nfv:virtualnetworkmanager xmlns:nfv="http://www.example.com/nfvInfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.com/nfvInfo nfvInfo.xsd">

	<nfv:catalog>
		<nfv:vnft name="WebClient_1" type="WebClient" memory="1024"
			disk="5120" />
		<nfv:vnft name="NAT_1" type="NAT" memory="6144" disk="8192" />
		<nfv:vnft name="Firewall_1" type="Firewall" memory="6144"
			disk="8192" />
		<nfv:vnft name="WebServer_1" type="WebServer" memory="8192"
			disk="10240" />
	</nfv:catalog>


	<nfv:nffg name="nffg_1" deployTime="2002-05-30T09:00:00">

		<nfv:node name="node_1" vnft="WebClient_1" />
		<nfv:node name="node_2" vnft="NAT_1" />
		<nfv:node name="node_3" vnft="Firewall_1" />
		<nfv:node name="node_4" vnft="WebServer_1" />

		<nfv:link name="link_12" src="node_1" dst="node_2" throughput="4"
			maxL="10" />
		<nfv:link name="link_21" src="node_2" dst="node_1" throughput="2"
			maxL="9" />
		<nfv:link name="link_23" src="node_2" dst="node_3" throughput="1"
			maxL="8" />
		<nfv:link name="link_32" src="node_3" dst="node_2" throughput="2"
			maxL="10" />
		<nfv:link name="link_34" src="node_3" dst="node_4" throughput="4"
			maxL="7" />
		<nfv:link name="link_43" src="node_4" dst="node_3" throughput="4"
			maxL="8" />

	</nfv:nffg>

	<nfv:in>
	
		<nfv:host name="host_1" maxVNF="3" disk="51200" memory="16384"
			nodes="node_1" />
		<nfv:host name="host_2" maxVNF="2" disk="51200" memory="16384"
			nodes="node_2" />
		<nfv:host name="host_3" maxVNF="2" disk="51200" memory="16384"
			nodes="node_3" />
		<nfv:host name="host_4" maxVNF="3" disk="51200" memory="16384"
			nodes="node_4" />

		<nfv:connection h2="host_1" h1="host_2" throughput="3"
			latency="8" />
		<nfv:connection h2="host_2" h1="host_3" throughput="3"
			latency="8" />
		<nfv:connection h2="host_3" h1="host_4" throughput="2"
			latency="9" />
	</nfv:in>


</nfv:virtualnetworkmanager>


<!-- This XML file was developed by Matteo Arzani for the Assignment 1 of 
	the course Distributed Programming II 2017/2018 in Politechnic University 
	of Turin. -->

=== M4TT30-4RZ4N1/DP2--2017-2018/Assignment1/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<virtualnetworkmanager xmlns="http://www.example.com/nfvInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/nfvInfo xsd/nfvInfo.xsd">
    <catalog>
        <vnft name="MAILCLIENTt" type="MAIL_CLIENT" memory="39" disk="310"/>
        <vnft name="WEBCLIENTt" type="WEB_CLIENT" memory="53" disk="120"/>
        <vnft name="MAILSERVERt" type="MAIL_SERVER" memory="410" disk="2600"/>
        <vnft name="WEBSERVERt" type="WEB_SERVER" memory="530" disk="7100"/>
        <vnft name="SPAMa" type="SPAM" memory="85" disk="120"/>
        <vnft name="SPAMb" type="SPAM" memory="56" disk="170"/>
    </catalog>
    <nffg name="Nffg3" deployTime="2016-09-28T17:43:20.000+02:00">
        <node name="WEBSERVERt0Nffg3" vnft="WEBSERVERt"/>
        <node name="MAILSERVERt1Nffg3" vnft="MAILSERVERt"/>
        <node name="SPAMb0Nffg3" vnft="SPAMb"/>
        <node name="MAILCLIENTt0Nffg3" vnft="MAILCLIENTt"/>
        <link name="Link2" src="WEBSERVERt0Nffg3" dst="SPAMb0Nffg3" throughput="0.0" maxL="0"/>
        <link name="Link4" src="MAILSERVERt1Nffg3" dst="SPAMb0Nffg3" throughput="0.0" maxL="0"/>
        <link name="Link1" src="SPAMb0Nffg3" dst="MAILCLIENTt0Nffg3" throughput="0.0" maxL="0"/>
        <link name="Link3" src="SPAMb0Nffg3" dst="WEBSERVERt0Nffg3" throughput="0.0" maxL="0"/>
        <link name="Link5" src="SPAMb0Nffg3" dst="MAILSERVERt1Nffg3" throughput="0.0" maxL="0"/>
        <link name="Link0" src="MAILCLIENTt0Nffg3" dst="SPAMb0Nffg3" throughput="0.0" maxL="0"/>
    </nffg>
    <nffg name="Nffg1" deployTime="2016-09-28T19:12:20.000+02:00">
        <node name="WEBCLIENTt2Nffg1" vnft="WEBCLIENTt"/>
        <node name="WEBSERVERt0Nffg1" vnft="WEBSERVERt"/>
        <node name="SPAMa2Nffg1" vnft="SPAMa"/>
        <node name="SPAMa0Nffg1" vnft="SPAMa"/>
        <node name="MAILCLIENTt1Nffg1" vnft="MAILCLIENTt"/>
        <node name="SPAMb3Nffg1" vnft="SPAMb"/>
        <node name="SPAMa1Nffg1" vnft="SPAMa"/>
        <node name="SPAMa5Nffg1" vnft="SPAMa"/>
        <node name="SPAMa4Nffg1" vnft="SPAMa"/>
        <node name="WEBCLIENTt0Nffg1" vnft="WEBCLIENTt"/>
        <link name="Link15" src="WEBCLIENTt2Nffg1" dst="SPAMb3Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link14" src="WEBCLIENTt2Nffg1" dst="SPAMa5Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link4" src="WEBCLIENTt2Nffg1" dst="SPAMa2Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link6" src="WEBSERVERt0Nffg1" dst="SPAMa4Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link5" src="SPAMa2Nffg1" dst="WEBCLIENTt2Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link16" src="SPAMa0Nffg1" dst="WEBCLIENTt0Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link13" src="SPAMa0Nffg1" dst="MAILCLIENTt1Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link2" src="MAILCLIENTt1Nffg1" dst="SPAMa1Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link10" src="SPAMb3Nffg1" dst="SPAMa4Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link11" src="SPAMa1Nffg1" dst="SPAMa2Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link1" src="SPAMa1Nffg1" dst="WEBCLIENTt0Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link3" src="SPAMa1Nffg1" dst="MAILCLIENTt1Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link9" src="SPAMa1Nffg1" dst="SPAMb3Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link12" src="SPAMa4Nffg1" dst="SPAMa5Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link17" src="SPAMa4Nffg1" dst="SPAMa2Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link7" src="SPAMa4Nffg1" dst="WEBSERVERt0Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link0" src="WEBCLIENTt0Nffg1" dst="SPAMa1Nffg1" throughput="0.0" maxL="0"/>
        <link name="Link8" src="WEBCLIENTt0Nffg1" dst="SPAMb3Nffg1" throughput="0.0" maxL="0"/>
    </nffg>
    <nffg name="Nffg0" deployTime="2016-09-26T18:48:20.000+02:00">
        <node name="SPAMb1Nffg0" vnft="SPAMb"/>
        <node name="SPAMa2Nffg0" vnft="SPAMa"/>
        <node name="WEBSERVERt0Nffg0" vnft="WEBSERVERt"/>
        <node name="MAILCLIENTt1Nffg0" vnft="MAILCLIENTt"/>
        <node name="WEBSERVERt1Nffg0" vnft="WEBSERVERt"/>
        <node name="SPAMa0Nffg0" vnft="SPAMa"/>
        <node name="WEBCLIENTt0Nffg0" vnft="WEBCLIENTt"/>
        <node name="SPAMa3Nffg0" vnft="SPAMa"/>
        <link name="Link7" src="SPAMb1Nffg0" dst="WEBSERVERt1Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link9" src="SPAMb1Nffg0" dst="SPAMa3Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link8" src="SPAMa2Nffg0" dst="WEBSERVERt0Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link4" src="WEBSERVERt0Nffg0" dst="SPAMa0Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link2" src="MAILCLIENTt1Nffg0" dst="SPAMa0Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link6" src="WEBSERVERt1Nffg0" dst="SPAMb1Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link1" src="SPAMa0Nffg0" dst="WEBCLIENTt0Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link3" src="SPAMa0Nffg0" dst="MAILCLIENTt1Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link5" src="SPAMa0Nffg0" dst="WEBSERVERt0Nffg0" throughput="0.0" maxL="0"/>
        <link name="Link0" src="WEBCLIENTt0Nffg0" dst="SPAMa0Nffg0" throughput="0.0" maxL="0"/>
    </nffg>
    <nffg name="Nffg2" deployTime="2016-09-26T13:16:20.000+02:00">
        <node name="WEBSERVERt0Nffg2" vnft="WEBSERVERt"/>
        <node name="MAILSERVERt1Nffg2" vnft="MAILSERVERt"/>
        <node name="WEBSERVERt2Nffg2" vnft="WEBSERVERt"/>
        <node name="MAILCLIENTt1Nffg2" vnft="MAILCLIENTt"/>
        <node name="MAILCLIENTt2Nffg2" vnft="MAILCLIENTt"/>
        <node name="SPAMb0Nffg2" vnft="SPAMb"/>
        <node name="WEBCLIENTt0Nffg2" vnft="WEBCLIENTt"/>
        <link name="Link6" src="WEBSERVERt0Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link8" src="MAILSERVERt1Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link10" src="WEBSERVERt2Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link2" src="MAILCLIENTt1Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link4" src="MAILCLIENTt2Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link11" src="SPAMb0Nffg2" dst="WEBSERVERt2Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link1" src="SPAMb0Nffg2" dst="WEBCLIENTt0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link3" src="SPAMb0Nffg2" dst="MAILCLIENTt1Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link5" src="SPAMb0Nffg2" dst="MAILCLIENTt2Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link7" src="SPAMb0Nffg2" dst="WEBSERVERt0Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link9" src="SPAMb0Nffg2" dst="MAILSERVERt1Nffg2" throughput="0.0" maxL="0"/>
        <link name="Link0" src="WEBCLIENTt0Nffg2" dst="SPAMb0Nffg2" throughput="0.0" maxL="0"/>
    </nffg>
    <in>
        <host name="H0" nodes="SPAMa2Nffg0 SPAMa2Nffg1 MAILCLIENTt2Nffg2 SPAMa0Nffg0 WEBCLIENTt2Nffg1 WEBSERVERt0Nffg3 WEBSERVERt0Nffg0 MAILSERVERt1Nffg2 SPAMa0Nffg1 SPAMb0Nffg2 SPAMb0Nffg3 SPAMa4Nffg1 WEBCLIENTt0Nffg1 WEBCLIENTt0Nffg0 WEBCLIENTt0Nffg2" maxVNF="18" disk="68000" memory="6500"/>
        <host name="H1" nodes="MAILCLIENTt1Nffg0 WEBSERVERt2Nffg2 MAILCLIENTt1Nffg1 SPAMb3Nffg1 MAILCLIENTt1Nffg2 SPAMa5Nffg1 WEBSERVERt1Nffg0 SPAMa3Nffg0 SPAMb1Nffg0 WEBSERVERt0Nffg2 MAILSERVERt1Nffg3 WEBSERVERt0Nffg1 SPAMa1Nffg1 MAILCLIENTt0Nffg3" maxVNF="18" disk="66000" memory="6900"/>
        <connection h1="H0" h2="H0" throughput="10.29" latency="0"/>
        <connection h1="H0" h2="H1" throughput="55.25" latency="21"/>
        <connection h1="H1" h2="H0" throughput="16.24" latency="21"/>
        <connection h1="H1" h2="H1" throughput="77.51" latency="0"/>
    </in>
</virtualnetworkmanager>
